name: Thesis Build
on:
  push:
    branches:
      - thesis

jobs:
  BundleBuild:
    name: Build thesis using latexmk
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build title page
        uses: xu-cheng/latex-action@v2
        with:
          root_file: config/titlepage/titlepage.tex
          extra_system_packages: "inkscape"
          latexmk_shell_escape: true
      - name: Upload title page
        uses: actions/upload-artifact@v3
        with:
          name: Titlepage
          path: titlepage.pdf
      - name: Fetch title page
        uses: actions/download-artifact@v3
        with:
          name: Titlepage
          path: config/titlepage
      - name: Build main document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: thesis.pdf
